### ISSUE TITLE
Synthetic Traffic Signs dataset

### ISSUE THREAD

**Issue by wogong** [Britefury/self-ensemble-visual-domain-adapt#10]
I am unable to find the Synthetic traffic signs data set on the internet. Could you please share your dataset? Thanks in advance.

Any share method is OK, I've created a dropbox file request for your convenience https://www.dropbox.com/request/GLgPzZDpSjOz8RRreZbT

**Comment by wogong** [comment]
You can find the dataset in http://graphics.cs.msu.ru/en/node/1337/

**Comment by Britefury** [comment]
Thank you for this!!!!

**Comment by Britefury** [comment]
I've updated README.md to include this link. Thanks again!

**Comment by wogong** [comment]
@Britefury You're welcome, thanks for your repo. Wish this may be helpful to those get here following the google search results :)
