### ISSUE TITLE
Getting the overall accuracies

### ISSUE THREAD

**Issue by d11r** [Britefury/self-ensemble-visual-domain-adapt#11]
I am running the SVHN -> MNIST case. This is the output:

`*** Epoch 9 took 68.69s: TRAIN clf loss=0.467770, unsup (tgt) loss=0.013310, conf mask=74.518%, unsup mask=74.518%; SRC TEST ERR=12.734%, TGT TEST student err=3.740%, TGT TEST teacher err=2.570%`

How could I get the following accuracies:
- mnist test accuracy
- svhn train accuracy
- svhn test accuracy

I tried figuring it out, you are using `batch_map_mean` but it seems to not give accuracy, but rather the log loss.

**Comment by dankirsdot** [comment]
According to the documentation function `batch_map_mean`
> Apply a function to all the samples that are accessed as mini-batches obtained from an iterator. Returns the across-samples mean of the results returned by 'func'

In the file 'experiment_domainadapt_meanteacher.py' the following lines calculates the mean classification errors for student and teacher network
`src_test_err_stu, src_test_err_tea = source_test_ds.batch_map_mean(f_eval_src, batch_size=batch_size * 2)`
`tgt_test_err_stu, tgt_test_err_tea = target_test_ds.batch_map_mean(f_eval_tgt, batch_size=batch_size * 2)`

As I understand you can find the accuracy as '1 - error'

**Comment by d11r** [comment]
@dankirsdot thanks for the reply, I understand the rationale but what is the accuracy as a whole, not accuracies of student and teacher separately.

**Comment by dankirsdot** [comment]
As I understand for your project

> 
    1. Accuracy on target domain is the goal.
    2. Accuracy on source domain is not important.

You need the accuracy of the teacher network because it will provide better results for the target domain. Anyway you can calculate both and compare.

**Comment by d11r** [comment]
That is correct. Thanks for the clarification.
