### ISSUE TITLE
Synthetic Traffic Signs data set link

### ISSUE THREAD

**Issue by roysubhankar** [Britefury/self-ensemble-visual-domain-adapt#4]
Hi I am unable to find the Synthetic traffic signs data set on the internet. Could you please share your data set link in the project page? Thanks in advance.

**Comment by roysubhankar** [comment]
I have found the dataset. Thank you.

**Comment by wogong** [comment]
@roysubhankar I can not find this dataset, can you share your dataset? many thanks!

————
update: found it, thanks!

**Comment by weiwang1988** [comment]
@roysubhankar Hi, I can't find this dataset either. I am wondering if you can share it to me. Thanks a lot!

**Comment by wogong** [comment]
@weiwang1988 You can find the link in readme.

**Comment by weiwang1988** [comment]
@wogong   Do you mean http://graphics.cs.msu.ru/en/node/1337/? But I can not open it, can you?

**Comment by weiwang1988** [comment]
@wogong  If possible, can you share the data to me? Thanks a lot!

**Comment by wogong** [comment]
hmm, the original link is dead. You can download from here
https://www.dropbox.com/s/2zuyr4ndduspxin/synthetic_data.zip?dl=0

**Comment by weiwang1988** [comment]
@wogong Got it. Thanks!

**Comment by Britefury** [comment]
I think that's SynDigits (the Dropbox link). [EDIT: this is incorrect]

@weiwang1988 Try:
https://drive.google.com/open?id=1wgLzFwrUOz0dLjuCWZ0ylDWQR0xTdJ9X

**Comment by wogong** [comment]
@Britefury You sure? (I made a mistake at first, but corrected seconds later :)

**Comment by Britefury** [comment]
Indeed; pardon me, I got the incorrect link in my email!
